version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - ".env"
    ports:
      - "5432:5432"

  redis:
    image: redis
    environment:
      - decode_responses=True
    ports:
      - "6379:6379"

  db-backup:
    image: postgres:14-alpine
    volumes:
      - ./backup-script.sh:/backup-script.sh  # Убедитесь, что скрипт исполняемый
      - ./backups:/backups
    env_file: .env
    entrypoint: /bin/sh
    command: -c "echo '* * * * * /backup-script.sh' | crontab - && crond -f"
    depends_on:
      - postgres

volumes:
  backups:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/backups
      o: bind